- mocks/wiremock/__files/prd/activeOrganisations.json
- mocks/wiremock/__files/prd/organisation1.json
- mocks/wiremock/__files/prd/organisation2.json
- mocks/wiremock/mappings/prd/organisation1ByInternalApi.json
- mocks/wiremock/mappings/prd/organisation2ByInternalApi.json
> Revert "fix: updated wiremock org data to match api tests"

- README.md
- bin/remove-stuck-pr.sh
- bin/run-tests-aat.sh
> feat: added useful scripts

- README.md
https://tools.hmcts.net/jira/browse/CMC-1728
Expands on the instructions for setting up a local environment as well as some clean up
```
[ ] Yes
[x] No
```
> fix: Update README (CMC-1728)

- bin/users.json
n/a
add respondent solicitor 2 user
```
[ ] Yes
[x] No
```
> fix: add respondent 2 solicitor user for e2e

- compose/backend.yml
- compose/case-document-am.yml
> Use ccd ase document ami api

- compose/backend.yml
N/A
- Adding env variable for AM Role Assignment `LD SDK KEY` 
- Adding CCD fix for multiparty on defendant response 1v2 solicitor journey
```
[ ] Yes
[x] No
```
> fix/Adding LD SDK Key env variable

- bin/add-services.sh
- Adding required roles for ExUI services, otherwise we are unable to login locally
```
[ ] Yes
[x] No
```
> ExUi Login Bug Fix

- bin/add-roles.sh
- bin/users.json
https://tools.hmcts.net/jira/browse/CIV-342
As part of the standard directions order work we need a new judge user role and a new judge user profile.
```
[ ] Yes
[x] No
```
> New role and user for judges

- compose/backend.yml
- database/Dockerfile
- update postgres version in Dockerfile
- also update it in backend.yml as it seems to not pick up the change from Dockerfile
```
[ ] Yes
[ ] No
```
> upgrade postgres version

- compose/xui.yml
https://tools.hmcts.net/jira/browse/EUI-5316
Fix Launch Darkly Client ID to resolve Local Issue
```
[x] Yes
[ ] No
```
> Fix Launch Darkly Client ID

- compose/xui.yml
https://tools.hmcts.net/jira/browse/EUI-5316
Set Launch Darkly Client ID
```
[X] Yes
[ ] No
```
> Fix Launch Darkly Client ID (#23)

- bin/process-and-import-apps-ccd-definition.sh
- bin/utils/process-definition.sh
- compose/xui.yml
> Adding General Apps Service URL and

- compose/backend.yml
- compose/elasticsearch.yml
Updated elastisearch image to 7.17.1
```
[ ] Yes
[X] No
```
> Updated elastisearch image to 7.17.1

- mocks/wiremock/mappings/fees-register/ga-fees-withNotice.json
- mocks/wiremock/mappings/fees-register/ga-fees-withoutNotice.json
https://tools.hmcts.net/jira/browse/CIV-2080
Mock the fee data for general application.
```
[ ] Yes
[ ] No
```
> CIV-2080 Adding fee-service mock for general application fees

- bin/add-roles.sh
- bin/am-role-assignments.json
- bin/users.json
New access profile
```
[ ] Yes
[x] No
```
> Updated role assignments and access profiles for GS_profile

- bin/users.json
Added missing comma in users.json
```
[ ] Yes
[x ] No
```
> fixed missing comma in users.json

- bin/add-roles.sh
- [.x ] commit messages are meaningful and follow good commit message guidelines
- [x ] README and other documentation has been updated / added (if needed)
- [x ] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/CIV-5331
Added ga-basic-access access profile
```
[ ] Yes
[x ] No
```
> added ga-basic-access access profile

- bin/add-roles.sh
- bin/am-role-assignments.json
- bin/users.json
- compose/xui.yml
- mocks/wiremock/__files/crd/case-flags-AAA6.json
- mocks/wiremock/__files/crd/case-flags-AAA7.json
- mocks/wiremock/__files/crd/party-flags-AAA6.json
- mocks/wiremock/__files/crd/party-flags-AAA7.json
- mocks/wiremock/__files/lrd/orgServices.json
- mocks/wiremock/mappings/crd/case-flags-AAA6.json
- mocks/wiremock/mappings/crd/case-flags-AAA7.json
- mocks/wiremock/mappings/crd/party-flags-AAA6.json
- mocks/wiremock/mappings/crd/party-flags-AAA7.json
- mocks/wiremock/mappings/lrd/orgServices.json
https://tools.hmcts.net/jira/browse/CIV-3419
Added LRD and CRD mocks for caseflags
```
[ ] Yes
[X] No
```
> CIV-3419 Create caseflags

- bin/import-bpmn-diagram.sh
https://tools.hmcts.net/jira/browse/CIV-6668
Add tenant id "civil"
```
[ ] Yes
[ ] No
```
> CIV-6668 add tenant-id to import-bpmn-diagram.sh

- mocks/wiremock/mappings/fees-register/ga-fees-appToVaryOrSuspend.json
https://tools.hmcts.net/jira/browse/CIV-3618
Add version field for vary judgement feeservice
```
[ ] Yes
[ ] No
```
> CIV-3618 Add Version field for vary fee

- mocks/wiremock/mappings/claimstore/claimantClaims.json
- mocks/wiremock/mappings/claimstore/defendantClaims.json
Change the CMC mock data to use the live service type.
```
[ ] Yes
[X] No
```
> CIV-8023 : Change date format

- mocks/wiremock/__files/hmc/listed-hearing.json
- mocks/wiremock/mappings/hmc/get-hearing.json
https://tools.hmcts.net/jira/browse/CIV-9344
Added hearing mocks
```
[ ] Yes
[X] No
```
> CIV-9344 Automated hearing notice process

- mocks/wiremock/mappings/fees-register/fee-range.json
https://tools.hmcts.net/jira/browse/CIV-2695
modified fee-range.json and added 2 new ranges for Fast Track Claims.
```
[ ] Yes
[x] No
```
> CIV-2695 - Updated fee-range.json

- compose/xui.yml
> Fixxuiidamissue

- mocks/wiremock/mappings/claimstore/claimantClaims.json
- mocks/wiremock/mappings/claimstore/defendantClaims.json
https://tools.hmcts.net/jira/browse/CIV-6250
Defendant response: Defendant dashboard status 
```
[ ] Yes
[X ] No
```
> CIV-6250:Defendant response defendant dashboard status

- compose/xui.yml
> Revert "Fixxuiidamissue"

- mocks/wiremock/mappings/hmc/put-parties-notified.json
https://tools.hmcts.net/jira/browse/CIV-7967
- add mocks for PUT request
```
[ ] Yes
[ ] No
```
> CIV-7967 PUT request to HMC

- bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-5339
added new profile
```
[ ] Yes
[x] No
```
> CIV-5339 - Release 2 - LIP v LIP Update Access Profile JSON

- bin/users.json
N/A
Fixed citizen role type and added one more user for Citizen just to avoid local changes in civil-service notification handler for LiP vs LiP claim.
```
[ ] Yes
[x] No
```
> CIV-0000 - Update users.json

- bin/users.json
> CIV-0000 add-users fix comma missing

- mocks/wiremock/mappings/claimstore/claimantClaims.json
- mocks/wiremock/mappings/claimstore/defendantClaims.json
Fixing for 
(java.time.format.DateTimeParseException) Text '2022-06-21T10:51:52.411212' could not be parsed, unparsed text found at index 10; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.LocalDate` from String "2022-06-21T10:51:52.411212": Failed to deserialize java.time.LocalDate: (java.time.format.DateTimeParseException) Text '2022-06-21T10:51:52.411212' could not be parsed, unparsed text found at index 10
at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 1796] (through reference chain: …
> CIV-0000 - Fix intentionToProceedDeadline format

- bin/add-roles.sh
> CIV- 0000 Update add-roles.sh

- mocks/wiremock/mappings/claimstore/claimantClaims.json
- mocks/wiremock/mappings/claimstore/defendantClaims.json
https://tools.hmcts.net/jira/browse/CIV-8903
CIV-8903 dashboard settlement agreement
```
[ ] Yes
[x ] No
```
> CIV-8903 updated Mock OCMC claims

- compose/cmc-ccd-definition-importer.yml
https://tools.hmcts.net/jira/browse/CIV-11947
```
[ ] Yes
[ ] No
```
> CIV-11947 Update cmc-ccd-definition-importer.yml 1.10.35

- compose/backend.yml
- database/Dockerfile
> Upgrade postgres versions for local development

- compose/camunda.yml
> Add environment variable to fix 400 History Time To Live Null

- compose/cmc-ccd-definition-importer.yml
https://tools.hmcts.net/jira/browse/SNI-4996
```
[ ] Yes
[ ] No
```
> SNI-4996 DQ not produced as a document in CCD

- README.md
- bin/add-roles.sh
- bin/add-services.sh
- bin/users.json
- bin/utils/create-ocmc-citizen-user.sh
- bin/utils/create-user.sh
- compose/defaults.conf
- compose/ocmc.yml
- compose/xui.yml
> CIV-0000: OCMC local setup

- bin/utils/idam-access-token.sh
- bin/utils/idam-authenticate.sh
- bin/utils/idam-lease-user-token.sh
replace stedolan/jq with mikefarah/yq
```
[ ] Yes
[ x] No
```
> CIV-00000 replace stedolan/jq with mikefarah/yq

- bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-13475
```
[ ] Yes
[ ] No
```
> CIV-13475 Add GA for LIP Access Profile

- bin/am-role-assignments.json
- bin/users.json
https://tools.hmcts.net/jira/browse/CIV-12764
add ga_ctsc_team_leader_national
```
[ ] Yes
[x] No
```
> CIV-12764 add ga_ctsc_team_leader_national

- mocks/wiremock/mappings/fees-register/ga-fees-certificateOfSatisfaction.json
> CIV-15070 Docmosis template update to extract application fee/s

- compose/ocmc.yml
https://tools.hmcts.net/jira/browse/DTSCCI-880
Remove Secrets
```
[ ] Yes
[ ] No
```
> remove secrets

- bin/add-roles.sh
https://tools.hmcts.net/jira/browse/CIV-15062
Add IDAM roles to script as ccd roles
```
[ ] Yes
[x] No
```
> CIV-15062 - add roles
